<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h3>Ooops! We could not find what you are loking for</h3>
                Not Found
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>
